### ISSUE TITLE
asking for help

### ISSUE THREAD

**Issue by madebycambiamentico** [avinashpaliwal/Super-SloMo#70]
So curious to see if it works but cannot understand what I'm missing: I have installed miniconda3, installed the libraries asked, but the torchvision versions seem to not be available for torch 0.4.1
By the way, running a slomo I get:
```
File "C:\Users\Nereo\Miniconda3\lib\site-packages\torchvision\models\inception.py", line 8, in <module>
    from torch.jit.annotations import Optional
ImportError: cannot import name 'Optional' from 'torch.jit.annotations' (C:\Users\Nereo\Miniconda3\lib\site-packages\torch\jit\annotations.py)
```

**Comment by wang99711123** [comment]
I also encountered such a problem, did you solve it?

**Comment by madebycambiamentico** [comment]
no. my understanding is that some required package of torch is so old that it is not available anymore. until super-slomo update its dependencies I fear we will never be able to use it...

**Comment by bmortella** [comment]
Try `pip install torchvision=0.1.6". That will install an older version of pytorch, the earliest available on pypi, which works with torch 0.4.1.

**Comment by avinashpaliwal** [comment]
I will soon update the installation instructions and requirements for more clarity.
